<script setup lang="ts">
import type { Dataset } from '../types/data'
defineProps<{ dataset:Dataset }>()
const base=useRuntimeConfig().app.baseURL
</script>
<template>
  <h2>Una exploración trazable</h2>
  <div v-if="dataset.analysis" class="notice"><strong>Escenario exploratorio V1 · 7 de octubre de 2026.</strong> El panorama reproduce el escenario del dashboard de referencia. Necesidad ajustada = 80 % de necesidad física + 20 % de pobreza monetaria normalizada. Presencia = promedio de cinco índices min–max de log(1 + tasa publicada). Brecha relativa = necesidad ajustada − presencia. Los rangos usan todos los dominios originales y los filtros no los recalculan. Los pesos son una propuesta; no validan cobertura, ejecución ni priorización oficial. Jefatura femenina y pobreza multidimensional permanecen como contexto. <a :href="`${base}documents/escenario-exploratorio-v1.md`" download>Descargar fórmulas y limitaciones</a></div>
  <div class="method-grid">
    <article><span>01</span><h3>Unidad de análisis</h3><p>El CSV preliminar contiene 95 dominios EM 2021: 80 UPZ y 15 agrupaciones, en 19 localidades. Sus 112 UPZ integrantes se identifican mediante codigos_upz. Una agrupación representa el dominio completo; no se reparten sus estimaciones entre UPZ.</p></article>
    <article><span>02</span><h3>Índices y sensibilidad</h3><p>Las cuatro dimensiones relativas del archivo están normalizadas entre 0 y 100. Se comprobó min–max sobre el proxy de tenencia, déficit cualitativo, proxy medio de entorno y algún riesgo reportado; el error de reproducción es menor a 0,000004 puntos por redondeo. El proxy de entorno coincide con la media de vía, iluminación y basuras.</p><p>El dashboard utiliza las tres columnas de necesidad publicadas, sin volver a normalizarlas. Su promedio con pesos iguales, doble vivienda y doble riesgo coincide con las dimensiones dentro de 0,000001 puntos. Para archivos personalizados se exige dirección explícita; faltantes y dimensiones constantes producen «Sin dato».</p></article>
    <article><span>03</span><h3>Propuesta frente a resultados preliminares</h3><p>El PDF propone riesgo integrado con POT, vulnerabilidad transversal, presencia ejecutada desde 2021, brecha y priorización. El CSV entregado tiene cuatro dimensiones y mantiene la pobreza y jefatura femenina como contexto. Presencia ejecutada, brecha, ranking y riesgo integrado validados están vacíos en las 95 filas: permanecen «Pendiente de validación».</p></article>
    <article><span>04</span><h3>Registros y unidades</h3><p>La encuesta corresponde a 2021. Las cinco líneas tienen períodos heterogéneos, sin un corte común. Vivienda está limitada a Plan Terrazas. Las tasas publicadas usan 1.000 hogares expandidos EM 2021; Barrios usa km². No se suman líneas como beneficiarios únicos ni se interpreta la presencia publicada como cobertura efectiva.</p></article>
    <article><span>05</span><h3>Cartografía y discrepancias</h3><p>Se agruparon multipartes oficiales SDP/Catastro según los códigos del CSV: 95 dominios, 112 UPZ, ninguna clave faltante. La equivalencia de límites con la EM 2021 requiere validación SIG. El GeoJSON adjunto de Barrios tiene 557 elementos y 233 IDs de intervención; el CSV suma 494 registros y 206 IDs distintos por dominio. El origen de esa diferencia y el cruce espacial permanecen pendientes.</p></article>
    <article><span>06</span><h3>Procedencia y cortes</h3><p>{{ dataset.source.name }}<br>Fecha de validación preliminar del archivo: {{ dataset.source.date || 'Sin verificar' }}<br>Licencia del CSV: {{ dataset.source.license || 'No declarada en los adjuntos' }}</p><p>La fecha 2026-10-06 no es un corte común de actuaciones. El PDF es una propuesta analítica, no una validación de las hipótesis. Los códigos de estado y riesgo se preservan sin asignarles etiquetas.</p></article>
  </div>
  <div class="download-actions"><a class="outline" :href="`${base}documents/propuesta-data-jam-cvp-2026.pdf`" target="_blank" rel="noopener noreferrer">Consultar propuesta PDF</a><a class="outline" :href="`${base}data/dominios.geojson`" download>GeoJSON de dominios</a><a class="outline" :href="`${base}data/intervenciones-barrios.geojson`" download>GeoJSON de Barrios adjunto</a><a class="outline" :href="`${base}data/geometry-provenance.json`" download>Procedencia cartográfica</a></div>
</template>
