<script setup lang="ts">
import { LayoutDashboard, Map, House, Layers, FileText, BookOpen, ChevronLeft, ChevronRight, Menu, ArrowUpRight, Download, Search, SlidersHorizontal, RotateCcw, Upload, Building2 } from 'lucide-vue-next'
import { dimensions, lines, type Row } from './types/data'
import { format, integral, need, total, value, numeric } from './utils/analytics'
import { distribution, scatter } from './utils/charts'
import { download } from './utils/csv'
const { dataset, loading, error, configured, filters, filtered, original, load, upload, applySchema, reset, downloadOriginal, downloadFiltered } = useTerritorialData()
const baseURL=useRuntimeConfig().app.baseURL
const sections = [
  { id: 'panorama', label: 'Panorama territorial', icon: LayoutDashboard, description: 'Una mirada conjunta al territorio, la necesidad habitacional y la presencia publicada.' },
  { id: 'mapa', label: 'Explorador geográfico', icon: Map, description: 'Consulta indicadores en geometrías oficiales de los dominios representativos.' },
  { id: 'necesidad', label: 'Necesidad habitacional', icon: House, description: 'Explora las cuatro dimensiones y la sensibilidad del índice a sus ponderaciones.' },
  { id: 'presencia', label: 'Presencia misional', icon: Layers, description: 'Registros publicados por las cinco líneas de la Caja de la Vivienda Popular.' },
  { id: 'ficha', label: 'Ficha territorial', icon: FileText, description: 'Indicadores, contexto y trazabilidad de cada dominio territorial.' },
  { id: 'metodologia', label: 'Metodología y fuentes', icon: BookOpen, description: 'Conoce los alcances, las fuentes y las decisiones de cálculo del observatorio.' }
]
const active = ref('panorama'), collapsed = ref(false), mobileOpen = ref(false), page = ref(1), selected = ref(''), order = ref('name')
const menuSections = sections.filter(section => !['necesidad', 'presencia', 'ficha'].includes(section.id))
const current = computed(() => sections.find(s => s.id === active.value)!)
const schema = computed(() => dataset.value.schema)
const get = (r: Row, key: string) => value(r, schema.value, key)
const localities = computed(() => [...new Set(dataset.value.rows.map(r => get(r, 'localidad')).filter(v => v !== null))].map(String).sort())
const domains = computed(() => dataset.value.rows.filter(r => !filters.locality || String(get(r, 'localidad')) === filters.locality))
const sorted = computed(() => [...filtered.value].sort((a,b) => order.value === 'need' ? (need(b, dataset.value.rows, schema.value) ?? -1) - (need(a, dataset.value.rows, schema.value) ?? -1) : String(get(a, 'nombre')).localeCompare(String(get(b, 'nombre')), 'es')))
const pages = computed(() => Math.max(1, Math.ceil(sorted.value.length / 10)))
const shown = computed(() => sorted.value.slice((page.value-1)*10, page.value*10))
const territory = computed(() => filtered.value.find(r => String(get(r,'codigo')) === selected.value))
const availableLines = computed(() => lines.filter(l => total(filtered.value, schema.value, `registros_${l.key}`) !== null))
const singleLine = computed(() => filters.line || 'barrios')
const scatterReady = computed(() => filtered.value.some(r => need(r, dataset.value.rows, schema.value) !== null && numeric(get(r, `registros_${singleLine.value}`)) !== null))
const localityCount = computed(() => new Set(filtered.value.map(r => get(r,'localidad')).filter(v => v !== null)).size)
const completeLines = computed(() => filtered.value.filter(r => integral(r, schema.value) === 5).length)
watch(filters, () => { page.value=1; selected.value='' }, { deep: true })
watch(() => filters.locality, () => { filters.domain='' })
watch(order, () => { page.value=1 })
onMounted(() => { const hash = window.location.hash.slice(1); if (sections.some(s => s.id===hash)) active.value=hash; window.addEventListener('hashchange', onHash) })
onBeforeUnmount(() => window.removeEventListener('hashchange', onHash))
function onHash() { const hash = window.location.hash.slice(1); if (sections.some(s => s.id===hash)) active.value=hash }
function navigate(id: string) { active.value=id; mobileOpen.value=false; window.location.hash=id }
function select(code: string) { selected.value=code; navigate('ficha') }
async function onUpload(e: Event) { const file=(e.target as HTMLInputElement).files?.[0]; if (file) await upload(file); (e.target as HTMLInputElement).value='' }
function exportConfig() { download('ubik2_esquema.json', JSON.stringify({ schema: schema.value, numericColumns: dataset.value.columns.filter(c => dataset.value.rows.some(r => typeof r[c] === 'number') || Object.entries(schema.value).some(([k,v]) => v===c && !['codigo','nombre','localidad','tipo','fuente','corte','limitaciones'].includes(k) && !k.startsWith('direccion_'))), source: dataset.value.source, analysis: dataset.value.analysis }, null,2), 'application/json') }
</script>
<template>
  <a class="skip-link" href="#contenido">Saltar al contenido</a>
  <div class="app-shell reference-layout" :class="{ collapsed, 'mobile-open': mobileOpen }">
    <button v-if="mobileOpen" class="scrim" aria-label="Cerrar navegación" @click="mobileOpen=false"/>
    <aside class="sidebar" aria-label="Navegación principal">
      <a href="#panorama" class="brand" aria-label="UBiK2, panorama territorial" @click.prevent="navigate('panorama')"><img :src="`${baseURL}brand/ubik2.png`" alt="UBiK2" class="project-logo"><span class="logo-caption">OBSERVATORIO<br>TERRITORIAL</span></a>
      <div class="header-actions"><span class="status-pill">DATOS REALES · PRELIMINARES</span><button class="outline" @click="navigate('metodologia')">Cómo leer los datos</button><button class="primary" :disabled="!original" @click="downloadOriginal">Descargar CSV</button></div>
      <div class="sidebar-divider"/><p class="nav-label">EXPLORAR EL OBSERVATORIO</p>
      <nav><a v-for="s in menuSections" :key="s.id" :href="`#${s.id}`" :class="{ active: active===s.id }" :aria-current="active===s.id ? 'page' : undefined" :title="s.label" @click.prevent="navigate(s.id)"><component :is="s.icon" :size="19"/><span>{{ s.label }}</span><ChevronRight v-if="active===s.id" :size="14" class="nav-arrow"/></a></nav>
      <div class="sidebar-bottom"><div class="institution"><span>CVP</span><p>Caja de la<br><strong>Vivienda Popular</strong></p></div><p class="sidebar-note">Datos para comprender<br>y transformar el territorio.</p><button class="collapse-button" :aria-label="collapsed ? 'Expandir barra lateral' : 'Plegar barra lateral'" :aria-expanded="!collapsed" @click="collapsed=!collapsed"><component :is="collapsed ? ChevronRight : ChevronLeft" :size="18"/><span>Plegar menú</span></button></div>
    </aside>
    <div class="workspace">
      <header v-if="active!=='panorama'" class="topbar"><div class="topbar-context"><button class="icon-button mobile-toggle" aria-label="Abrir navegación" @click="mobileOpen=true"><Menu :size="22"/></button><span>Observatorio territorial</span><span class="separator">/</span><strong>{{ current.label }}</strong></div><div class="topbar-right"><span class="status-pill"><i/>Exploración preliminar</span><span class="city-label">BOGOTÁ, D. C.</span></div></header>
      <main id="contenido" tabindex="-1">
        <div v-if="active!=='panorama'" class="page-heading"><div><div class="section-label">UBiK2 / DATA JAM CVP 2026</div><h1>{{ current.label }}</h1><p>{{ current.description }}</p></div><button class="outline export" :disabled="!filtered.length" @click="downloadFiltered"><Download :size="16"/>Exportar resultados</button></div>
        <div v-if="active!=='panorama'" class="notice intro-notice"><span class="notice-symbol">i</span><p><strong>Una lectura exploratoria, con contexto.</strong> La necesidad se basa en la EM 2021. La presencia publicada tiene períodos heterogéneos y no equivale a cobertura efectiva.</p><a href="#metodologia" @click.prevent="navigate('metodologia')">Ver metodología <ArrowUpRight :size="15"/></a></div>
        <section v-if="active!=='panorama'" class="panel filter-panel" aria-label="Filtros territoriales"><div class="filter-heading"><span><SlidersHorizontal :size="16"/>Filtros de exploración</span><button class="text-button" @click="reset"><RotateCcw :size="14"/>Limpiar filtros</button></div><div class="filters"><label>Localidad<select aria-label="Localidad" v-model="filters.locality" :disabled="!configured"><option value="">Todas las localidades</option><option v-for="l in localities" :key="l">{{ l }}</option></select></label><label>Dominio representativo<select aria-label="Dominio representativo" v-model="filters.domain" :disabled="!configured"><option value="">Todos los dominios</option><option v-for="r in domains" :key="String(get(r,'codigo'))" :value="String(get(r,'codigo'))">{{ get(r,'nombre') }}</option></select></label><label>Línea misional<select aria-label="Línea misional" v-model="filters.line" :disabled="!configured"><option value="">Todas las líneas</option><option v-for="l in lines" :key="l.key" :value="l.key">{{ l.label }}</option></select></label><label>Buscar territorio<div class="search-input"><Search :size="16"/><input v-model="filters.search" :disabled="!configured" placeholder="Nombre o código"></div></label></div><p class="filter-note">El filtro por línea conserva dominios con registros publicados mayores a cero.</p></section>
        <div v-if="error" role="alert" class="notice error">{{ error }} <button class="text-button" @click="load">Reintentar carga inicial</button></div>
        <div v-if="loading" role="status" class="panel loading">Cargando datos territoriales…</div>
        <section v-else-if="!configured" class="panel data-pending"><div class="data-pending-icon"><Upload :size="23"/></div><div><h2>{{ dataset.rows.length ? 'Asigna las columnas para comenzar' : 'Los datos reales son el punto de partida' }}</h2><p>{{ dataset.rows.length ? 'Revisa los encabezados y su diccionario antes de calcular los indicadores.' : 'El CSV y el PDF de la propuesta no están disponibles en este repositorio. No se muestran cifras simuladas.' }}</p></div><label class="upload-button">Cargar CSV<input type="file" accept=".csv,text/csv" @change="onUpload"></label></section>
        <SchemaMapper v-if="dataset.columns.length && (active==='metodologia' || !configured)" :key="original" :dataset="dataset" @apply="applySchema"/>
        <ObservatoryOverview v-if="active==='panorama' && configured" :dataset="dataset" :rows="filtered" :filters="filters" :configured="configured" @update-filters="Object.assign(filters,$event)" @reset="reset" @select="select" @navigate="navigate"/>
        <ClientOnly v-if="active==='mapa'"><LazyTerritorialMap :dataset="dataset" :rows="filtered" :line="filters.line" @select="select"/></ClientOnly>
        <AnalyticalModel v-if="active==='necesidad' || active==='metodologia'"/>
        <section v-if="active==='necesidad'" class="panel"><h2>Sensibilidad de las ponderaciones</h2><p>El CSV preliminar ya aporta las dimensiones relativas y los tres escenarios de necesidad en escala 0–100. Se muestran sin renormalizar. Para CSV personalizados se aplica min–max sobre todos los dominios con dirección explícita.</p><div class="weight-grid"><div><strong>Pesos iguales</strong><p>Tenencia 25% · vivienda 25%<br>entorno 25% · riesgo 25%</p></div><div><strong>Doble peso de vivienda</strong><p>Vivienda 40%<br>otras dimensiones 20% cada una</p></div><div><strong>Doble peso de riesgo</strong><p>Riesgo 40%<br>otras dimensiones 20% cada una</p></div></div><p class="muted">Pobreza y jefatura femenina son contexto diferencial y no están incorporadas. El resultado no constituye una priorización institucional validada.</p><div class="table-scroll"><table><caption>Comparación de escenarios · valores de 0 a 100</caption><thead><tr><th>Dominio</th><th v-for="d in dimensions" :key="d">{{ d }}</th><th>Iguales</th><th>Vivienda ×2</th><th>Riesgo ×2</th><th>Pobreza</th><th>Jefatura femenina</th></tr></thead><tbody><tr v-for="r in shown" :key="String(get(r,'codigo'))"><th>{{ get(r,'nombre') }}</th><td v-for="d in dimensions" :key="d">{{ format(get(r,d)) }}</td><td>{{ format(need(r,dataset.rows,schema)) }}</td><td>{{ format(need(r,dataset.rows,schema,'housing')) }}</td><td>{{ format(need(r,dataset.rows,schema,'risk')) }}</td><td>{{ format(get(r,'pobreza')) }}</td><td>{{ format(get(r,'jefatura')) }}</td></tr></tbody></table></div></section>
        <section v-if="active==='presencia'" class="panel"><h2>Cinco líneas, diferentes unidades de registro</h2><p>La tabla territorial y las fichas distinguen conteos publicados, tasas disponibles, identificadores distintos y actuaciones ejecutadas. No se deducen ejecuciones desde códigos sin diccionario.</p><div class="line-grid"><article v-for="line in lines.filter(l=>!filters.line || l.key===filters.line)" :key="line.key"><span class="line-dot" :style="{ background: line.color }"/><h3>{{ line.label }}</h3><strong>{{ format(total(filtered,schema,`registros_${line.key}`)) }}</strong><small>Registros disponibles (suma parcial si hay nulos)</small><p>{{ filtered.filter(r=>numeric(get(r,`registros_${line.key}`))!==null).length }} de {{ filtered.length }} dominios con dato</p></article></div><PublishedHousing v-if="dataset.analysis && (!filters.line || filters.line==='vivienda')" :rows="filtered"/><div class="notice">Mejoramiento de Vivienda: el CSV declara SOLO_PLAN_TERRAZAS. Las asistencias técnicas ejecutadas no equivalen a obras terminadas. Ausencia de registros CVP no implica ausencia del Estado.</div></section>
        <template v-if="active==='ficha'"><TerritoryCard v-if="territory" :row="territory" :dataset="dataset"/><EmptyState v-else class="panel" title="Selecciona un dominio territorial" description="Abre una ficha desde la tabla inferior o selecciona un polígono coincidente en el explorador."/></template>
        <section v-if="active==='metodologia'" class="panel methodology"><MethodologyPanel :dataset="dataset"/><div class="download-actions"><label class="upload-button">Actualizar CSV<input type="file" accept=".csv,text/csv" @change="onUpload"></label><button class="outline" :disabled="!original" @click="downloadOriginal"><Download :size="16"/>CSV original</button><button class="outline" :disabled="!filtered.length" @click="downloadFiltered">Resultados filtrados</button><button class="outline" :disabled="!configured" @click="exportConfig">Descargar esquema</button></div><SourcesPanel/></section>
        <section v-if="active!=='metodologia' && active!=='panorama'" class="panel territories"><div class="panel-heading"><div><h2>Dominios territoriales</h2><p>{{ configured ? filtered.length : '—' }} dominios en la selección · {{ configured ? dataset.rows.length : '—' }} en el archivo</p></div><label class="sort-label">Ordenar<select aria-label="Ordenar dominios" v-model="order"><option value="name">Nombre del dominio</option><option value="need">Necesidad exploratoria (desc.)</option></select></label></div><div v-if="shown.length" class="table-scroll"><table><caption class="sr-only">Dominios seleccionados y presencia por línea</caption><thead><tr><th>Dominio / código</th><th>Localidad</th><th>Tipo</th><th>Necesidad exploratoria</th><th>Integralidad</th><th v-for="l in lines" :key="l.key">{{ l.label }}</th><th>Consulta</th></tr></thead><tbody><tr v-for="r in shown" :key="String(get(r,'codigo'))"><th>{{ get(r,'nombre') }}<small class="block muted">{{ get(r,'codigo') }}</small></th><td>{{ get(r,'localidad') }}</td><td><span class="tag">{{ get(r,'tipo') }}</span></td><td>{{ format(need(r,dataset.rows,schema)) }}</td><td>{{ format(integral(r,schema)) }}</td><td v-for="l in lines" :key="l.key">{{ format(get(r,`registros_${l.key}`)) }}</td><td><button class="text-button" :aria-label="`Ver ficha de ${get(r,'nombre')}`" @click="select(String(get(r,'codigo')))">Ver ficha <ArrowUpRight :size="14"/></button></td></tr></tbody></table></div><EmptyState v-else :title="configured ? 'No hay dominios en esta selección' : 'El territorio espera sus datos'" :description="configured ? 'Prueba otra búsqueda o limpia los filtros para ver los dominios disponibles.' : 'Carga el CSV original para consultar indicadores y fichas territoriales con trazabilidad.'"/><div class="pagination"><span>Resultados {{ shown.length ? (page-1)*10+1 : 0 }}–{{ Math.min(page*10,filtered.length) }} de {{ filtered.length }}</span><div><button class="icon-button" aria-label="Página anterior" :disabled="page<=1" @click="page--"><ChevronLeft :size="17"/></button><span>Página {{ page }} de {{ pages }}</span><button class="icon-button" aria-label="Página siguiente" :disabled="page>=pages" @click="page++"><ChevronRight :size="17"/></button></div></div></section>
        <footer class="footer"><span><strong>UBiK2</strong> · Caja de la Vivienda Popular</span><span>Observatorio territorial · Datos preliminares sujetos a validación</span></footer>
      </main>
    </div>
  </div>
</template>
