import { chromium } from '@playwright/test'
import { createServer } from 'node:http'
import fs from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'
const root = path.resolve('.output/public')
const base=process.env.VERIFY_BASE_URL || '/'
const server = createServer(async(req,res)=> {
  try {
    const requested=decodeURIComponent(new URL(req.url,'http://localhost').pathname)
    if(!requested.startsWith(base)) {res.writeHead(404).end(); return}
    const pathname=`/${requested.slice(base.length)}`
    const file=path.resolve(root, `.${pathname === '/' ? '/index.html' : pathname}`)
    if (!file.startsWith(root + path.sep)) { res.writeHead(403).end(); return }
    const types={ '.html':'text/html', '.js':'text/javascript', '.css':'text/css', '.json':'application/json', '.svg':'image/svg+xml', '.png':'image/png' }
    res.setHeader('Content-Type', types[path.extname(file)] || 'application/octet-stream'); res.end(await fs.readFile(file))
  } catch { res.writeHead(404).end() }
})
await new Promise(resolve=>server.listen(4173,'127.0.0.1',resolve))
let browser, page
try {
  browser=await chromium.launch({ channel:'msedge', headless:true })
  page=await browser.newPage({ viewport: { width:1440,height:1100 } })
  const errors=[]; page.on('pageerror',e=>errors.push(e.stack||e.message))
  await page.goto(`http://127.0.0.1:4173${base}`)
  await page.getByRole('heading',{name:'Las necesidades tienen un lugar.',exact:true}).waitFor()
  await page.locator('.overview-map').getByText('Gris: sin dato · 95 geometrías coincidentes',{exact:true}).waitFor()
  await fs.mkdir('artifacts', { recursive:true })
  await page.screenshot({ path:'artifacts/desktop.png', fullPage:true })
  assert.equal(await page.getByLabel('Indicador del mapa',{exact:true}).inputValue(),'scenario:gap')
  assert.equal(await page.locator('.territory-result-cards button').count(),4)
  await page.locator('.territory-result-cards button').first().click()
  assert.equal(await page.getByLabel('Indicador del mapa',{exact:true}).inputValue(),'scenario:need')
  await page.getByLabel('Indicador del mapa',{exact:true}).selectOption('raw:pct_deficit_cualitativo')
  await page.locator('.additional-comparison > summary').click()
  const barsDoNotOverlap = () => page.locator('.territory-charts .territory-bar').evaluateAll(rows=>rows.every(row=>{
    const cells=[...row.children].map(cell=>cell.getBoundingClientRect())
    return cells.every((cell,index)=>index===0 || cell.left>=cells[index-1].right)
  }))
  assert.equal(await barsDoNotOverlap(),true)
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true)
  await page.locator('.overview-territory').getByRole('heading',{name:'Lucero',exact:true}).waitFor()
  await page.locator('.overview-territory .territory-context').getByText('Jefatura femenina',{exact:true}).waitFor()
  await page.locator('.overview-map-column .territory-charts').getByRole('heading',{name:'Lucero',exact:true}).waitFor()
  await page.locator('.territory-charts').getByRole('button',{name:'Ver Tenencia en el mapa',exact:true}).click()
  assert.equal(await page.getByLabel('Indicador del mapa',{exact:true}).inputValue(),'tenencia')
  await page.locator('.territory-charts').getByRole('button',{name:'Ver Jefatura femenina en el mapa',exact:true}).click()
  assert.equal(await page.getByLabel('Indicador del mapa',{exact:true}).inputValue(),'raw:pct_jefatura_femenina')
  assert.equal(await page.locator('.territory-charts').getByRole('button',{name:'Ver Vulnerabilidad en el mapa',exact:true}).isDisabled(),false)
  await page.getByLabel('Indicador del mapa',{exact:true}).selectOption('raw:pct_jefatura_femenina')
  await page.locator('.territory-highlight').getByText('Jefatura femenina',{exact:true}).waitFor()
  await page.getByLabel('Eje horizontal (X)',{exact:true}).selectOption('raw:pct_jefatura_femenina')
  await page.getByLabel('Indicador del mapa',{exact:true}).selectOption('raw:pct_deficit_cualitativo')
  await page.getByRole('button',{name:'Seleccionar La Flora',exact:true}).click()
  await page.locator('.overview-territory').getByRole('heading',{name:'La Flora',exact:true}).waitFor()
  await page.locator('.territory-charts').getByRole('heading',{name:'La Flora',exact:true}).waitFor()
  await page.getByLabel('Busca una UPZ o agrupación',{exact:true}).fill('Corabastos')
  await page.locator('.territory-result-cards button').first().getByText('47,2',{exact:false}).waitFor()
  await page.locator('.territory-result-cards button').nth(1).getByText('22',{exact:false}).waitFor()
  await page.locator('.territory-result-cards button').nth(2).getByText('25,2',{exact:false}).waitFor()
  await page.locator('.territory-result-cards button').nth(3).getByText('74,5',{exact:false}).waitFor()
  await page.screenshot({path:'artifacts/reference-corabastos.png',fullPage:true})
  await page.getByLabel('Busca una UPZ o agrupación',{exact:true}).fill('')
  await page.getByRole('button',{name:'Seleccionar territorio Lucero',exact:true}).click()
  await page.locator('.overview-territory').getByRole('heading',{name:'Lucero',exact:true}).waitFor()
  await page.locator('.scatter-comparison .chart canvas').waitFor()
  await page.getByLabel('Eje horizontal (X)',{exact:true}).selectOption('raw:pct_pobreza_monetaria_hogares')
  await page.getByLabel('Eje vertical (Y)',{exact:true}).selectOption('raw:pct_deficit_cualitativo')
  const pointsEvent=page.waitForEvent('download')
  await page.getByRole('button',{name:'Exportar puntos',exact:true}).click()
  await (await pointsEvent).saveAs('artifacts/scatter.csv')
  assert.equal((await fs.readFile('artifacts/scatter.csv','utf8')).split('\r\n').length,96)
  await page.getByRole('button',{name:'Intercambiar ejes',exact:true}).click()
  assert.equal(await page.getByLabel('Eje horizontal (X)',{exact:true}).inputValue(),'raw:pct_deficit_cualitativo')
  await page.screenshot({path:'artifacts/scatter-desktop.png',fullPage:true})
  await page.getByLabel('Líneas CVP con registros',{exact:true}).selectOption('5')
  await page.getByText('Gris: sin dato · 9 geometrías coincidentes',{exact:true}).waitFor()
  await page.getByRole('button',{name:'Restablecer filtros',exact:true}).click()
  await page.getByLabel('Localidad del mapa',{exact:true}).selectOption('Usaquén')
  await page.getByText('Gris: sin dato · 7 geometrías coincidentes',{exact:true}).waitFor()
  await page.getByLabel('Indicador del mapa',{exact:true}).selectOption('raw:pct_pobreza_monetaria_hogares')
  await page.locator('.overview-comparison').getByText('Hogares con pobreza monetaria',{exact:false}).first().waitFor({state:'attached'})
  const selectionEvent=page.waitForEvent('download')
  await page.getByRole('button',{name:'Exportar selección',exact:true}).click()
  await (await selectionEvent).saveAs('artifacts/overview-selection.csv')
  assert.equal((await fs.readFile('artifacts/overview-selection.csv','utf8')).split('\r\n').length,8)
  await page.getByRole('button',{name:'Restablecer filtros',exact:true}).click()
  await page.getByLabel('Indicador del mapa',{exact:true}).selectOption('raw:pct_deficit_cualitativo')
  await page.locator('nav').getByRole('link',{name:'Explorador geográfico',exact:true}).click()
  await page.getByText('Gris: sin dato · 95 geometrías coincidentes',{exact:true}).waitFor()
  await page.getByRole('checkbox',{name:'Superponer elementos de Barrios',exact:false}).check()
  await page.getByText('Azul: 557 elementos cartográficos',{exact:false}).waitFor()
  await page.screenshot({path:'artifacts/map-real.png',fullPage:true})
  await page.locator('.filter-panel').getByLabel('Localidad',{exact:true}).selectOption('Usaquén')
  await page.getByText('Azul: 17 elementos cartográficos',{exact:false}).waitFor()
  await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click()
  await page.locator('nav').getByRole('link',{name:'Panorama territorial',exact:true}).click()
  await page.getByLabel('Busca una UPZ o agrupación',{exact:true}).fill('Castilla')
  await page.locator('.overview-territory').getByRole('heading',{name:'KENNEDY: Castilla + Bavaria',exact:true}).waitFor()
  await page.getByRole('button',{name:'Ver ficha completa',exact:false}).click()
  await page.locator('.territory-card').getByText('grupo_UPZ',{exact:false}).waitFor()
  await page.locator('.territory-card').getByText('Pendiente de validación',{exact:true}).first().waitFor()
  await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click()
  await page.locator('nav').getByRole('link',{name:'Asistente de datos',exact:true}).click()
  await page.getByLabel('Tipo de asistente',{exact:true}).selectOption('local')
  await page.getByRole('button',{name:'¿Cuántos registros de Barrios hay en Usaquén?',exact:true}).click()
  await page.locator('.assistant-answer').getByText(/registros publicados de Mejoramiento de Barrios/).waitFor()
  await page.getByLabel('Tu pregunta',{exact:true}).fill('Compara la necesidad de UPZ 9 y UPZ 11')
  await page.getByLabel('Tu pregunta',{exact:true}).press('Enter')
  assert.equal(await page.locator('.assistant-message').last().locator('tbody tr').count(),2)
  await page.getByLabel('Tu pregunta',{exact:true}).fill('Y vivienda')
  await page.getByRole('button',{name:'Consultar datos',exact:true}).click()
  await page.locator('.assistant-message').last().getByText('Vivienda · dimensión relativa · 0–100',{exact:true}).waitFor()
  const conversationEvent=page.waitForEvent('download')
  await page.getByRole('button',{name:'Descargar conversación',exact:true}).click()
  await (await conversationEvent).saveAs('artifacts/conversation.json')
  const conversation=JSON.parse(await fs.readFile('artifacts/conversation.json','utf8'))
  assert.equal(conversation.messages.length,3)
  assert.deepEqual(conversation.messages[2].answer.fields,['indice_vivienda_relativo'])
  await page.getByLabel('Dominio representativo',{exact:true}).selectOption('802')
  // Consulta todo el archivo y abre una ficha fuera del filtro actual.
  await page.locator('.assistant-message').last().getByRole('button',{name:'Ver ficha',exact:true}).first().click()
  await page.locator('.territory-card').getByRole('heading',{name:/Verbenal|San Cristóbal Norte/}).waitFor()
  await page.locator('nav').getByRole('link',{name:'Asistente de datos',exact:true}).click()
  assert.equal(await page.locator('.assistant-message').count(),3)
  await page.getByRole('button',{name:'¿Cómo se calcula la brecha?',exact:true}).click()
  await page.locator('.assistant-message').last().getByText(/Brecha = necesidad − presencia/).waitFor()
  await page.setViewportSize({width:390,height:844})
  await page.screenshot({path:'artifacts/assistant-mobile.png',fullPage:true})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  await page.setViewportSize({width:1440,height:1100})
  await page.locator('.filter-panel').getByLabel('Localidad',{exact:true}).selectOption('Usaquén')
  await page.getByLabel('Alcance de las preguntas',{exact:true}).selectOption('filtered')
  await page.getByLabel('Tu pregunta',{exact:true}).fill('Necesidad en Kennedy')
  await page.getByLabel('Tu pregunta',{exact:true}).press('Enter')
  await page.locator('.assistant-message').last().getByText(/No hay dominios para esta consulta/).waitFor()
  await page.screenshot({path:'artifacts/assistant-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click()
  await page.setViewportSize({width:390,height:844})
  await page.locator('nav').getByRole('link',{name:'Panorama territorial',exact:true}).click()
  await page.locator('.overview-map').getByText('Gris: sin dato · 95 geometrías coincidentes',{exact:true}).waitFor()
  await page.screenshot({path:'artifacts/mobile-real.png',fullPage:true})
  assert.equal(await barsDoNotOverlap(),true)
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  await page.setViewportSize({width:1440,height:1100})
  await page.locator('nav').getByRole('link',{name:'Metodología y fuentes',exact:true}).click()
  // Archivo artificial de prueba; nunca se incorpora al conjunto público.
  const headers=['codigo','nombre','localidad','tipo','tenencia','vivienda','entorno','riesgo','barrios','mv','cps','tp','reas','brecha','ranking','ejec']
  const testRows=Array.from({length:12},(_,i)=>[String(i+1).padStart(3,'0'),`Dominio de prueba ${String(i+1).padStart(2,'0')}`,i<6?'Localidad A':'Localidad B',i%2?'Agrupación UPZ':'UPZ individual',i,12-i,i*2,i*3,i===0?0:i,1,2,3,4,'','',''])
  const csv=[headers.join(','),...testRows.map(r=>r.join(','))].join('\n')
  await page.locator('.methodology input[type=file]').setInputFiles({ name:'prueba.csv', mimeType:'text/csv', buffer:Buffer.from(csv) })
  await page.locator('.mapper').waitFor()
  for (const [label,column] of [['Código de dominio','codigo'],['Nombre del dominio','nombre'],['Localidad','localidad'],['Tipo de dominio','tipo'],['Dimensión: tenencia','tenencia'],['Dimensión: vivienda','vivienda'],['Dimensión: entorno','entorno'],['Dimensión: riesgo','riesgo'],['Registros: Mejoramiento de Barrios','barrios'],['Registros: Mejoramiento de Vivienda','mv'],['Registros: Curaduría Pública Social','cps'],['Registros: Titulación Predial','tp'],['Registros: Reasentamientos','reas'],['Brecha validada','brecha'],['Ranking validado','ranking'],['Actuaciones ejecutadas: Mejoramiento de Barrios','ejec']]) await page.locator('.mapper').getByLabel(label,{exact:true}).selectOption(column)
  for (const key of ['tenencia','vivienda','entorno','riesgo']) await page.getByLabel(`Mayor necesidad en ${key}`,{exact:true}).selectOption('alta')
  await page.getByRole('button',{ name:'Aplicar asignación',exact:true }).click()
  await page.evaluate(()=>{ window.location.hash='presencia' })
  await page.getByText('Página 1 de 2',{exact:true}).waitFor()
  await page.getByRole('button',{name:'Página siguiente',exact:true}).click()
  await page.getByText('Página 2 de 2',{exact:true}).waitFor()
  await page.locator('.filter-panel').getByLabel('Localidad',{exact:true}).selectOption('Localidad A')
  await page.getByText('Resultados 1–6 de 6',{exact:true}).waitFor()
  await page.getByLabel('Línea misional',{exact:true}).selectOption('barrios')
  await page.getByText('Resultados 1–5 de 5',{exact:true}).waitFor()
  await page.getByLabel('Buscar territorio',{exact:true}).fill('inexistente')
  await page.getByText('No hay dominios en esta selección',{exact:true}).waitFor()
  await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click()
  const downloadEvent=page.waitForEvent('download')
  await page.getByRole('button',{name:'Exportar resultados',exact:true}).click()
  const downloaded=await downloadEvent; await downloaded.saveAs('artifacts/filtered.csv')
  assert.equal((await fs.readFile('artifacts/filtered.csv','utf8')).split('\r\n').length,13)
  await page.getByRole('button',{name:'Ver ficha de Dominio de prueba 01',exact:true}).click()
  await page.locator('.territory-card').getByText('Pendiente de validación',{exact:true}).first().waitFor()
  await page.locator('nav').getByRole('link',{name:'Explorador geográfico',exact:true}).click()
  await page.getByText('Geometrías pendientes de verificación',{exact:true}).waitFor()
  // Polígono de prueba del dominio completo; solo ejercita el importador y no se publica.
  const geo={type:'FeatureCollection',features:[{type:'Feature',properties:{domain:'001'},geometry:{type:'Polygon',coordinates:[[[-74.12,4.6],[-74.10,4.6],[-74.10,4.62],[-74.12,4.62],[-74.12,4.6]]]}}]}
  await page.locator('input[accept=".geojson,.json"]').setInputFiles({name:'prueba.geojson',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(geo))})
  await page.getByLabel('Propiedad con código de dominio',{exact:true}).selectOption('domain')
  await page.getByLabel('Procedencia oficial / licencia',{exact:true}).fill('Procedencia ficticia solo para prueba automatizada')
  await page.getByRole('checkbox').check()
  await page.getByText('Gris: sin dato · 1 geometrías coincidentes',{exact:true}).waitFor()
  assert.equal(await page.locator('.leaflet-interactive').count(),1)
  await page.locator('.leaflet-interactive').click()
  await page.locator('.territory-card').getByRole('heading',{name:'Dominio de prueba 01',exact:true}).waitFor()
  await page.setViewportSize({width:390,height:844})
  await page.locator('nav').getByRole('link',{name:'Panorama territorial',exact:true}).click()
  await page.getByRole('heading',{name:'Las necesidades tienen un lugar.',exact:true}).waitFor()
  await page.screenshot({path:'artifacts/mobile-loaded.png',fullPage:true})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true)
  assert.deepEqual(errors,[])
  console.log('UI verificada: nuevo panorama con mapa/ficha, indicadores originales, filtros de integralidad y localidad, comparación y exportación; asistente; 95 dominios reales, 557 intervenciones (17 en Usaquén), agrupaciones, escritorio/móvil; importación alternativa, paginación y descarga; sin errores JavaScript.')
} catch(e) { await page?.screenshot({path:'artifacts/failure.png',fullPage:true}); if(page) await fs.writeFile('artifacts/failure.html',await page.content()); throw e }
finally { await browser?.close(); await new Promise(resolve=>server.close(resolve)) }
